### ISSUE TITLE
Question about AveragePerplexity

### ISSUE THREAD

**Issue by xiulinyang** [Yixiao-Song/SLING_Data_Code#1]
Hi Yixiao,

Thanks a lot for providing the evaluation code and interesting dataset for Chinese linguistic evaluation. I have a question regarding the function ```AveragePerplexity```. My understanding is that this function calculates the average perplexity for each category, but I was wondering why it doesn’t simply take the negative average of the perplexity list instead (given that the values in the perplexity list are negative perplexity). I’m curious why, after obtaining the negative perplexity, the function then calculates the probability before determining the perplexity. I wanted to clarify this in case there’s something I’m missing.

Thanks again!

```python
def AveragePerplexity(perplexity_list):
    neg_log_prob_sum = 0
    count = 0

    for i in perplexity_list:
        neg_log_prob = torch.log(-i)
        neg_log_prob_sum += neg_log_prob
        count += 1

    ave_neg_log_prob = neg_log_prob_sum/count
    ave_ppl = torch.exp(ave_neg_log_prob)

    return -ave_ppl
```

**Comment by Yixiao-Song** [comment]
Hi Xiulin,

Thank you for your email! And sorry for the late reply.

For the average perplexity, I converted the perplexity of each sentence to
probability, took the average of the probabilities, and then converted the
average probability back to perplexity. I did that because perplexity is on
an exponential scale. Averaging perplexity directly is mathematically
unsound.

Hope this helps.
Best,
Yixiao

**Comment by xiulinyang** [comment]
Got it, thanks for explaining! Just one more question—did you make the perplexity results negative on purpose?

**Comment by Yixiao-Song** [comment]
Hi Xiulin,

Yes, I did it on purpose. It was my first project and my head wasn't able
to wrap around the idea that perplexity is "the lower the better". So I
converted perplexity to negative. In retrospect, it wasn't a good idea.

Best,
Yixiao

**Comment by xiulinyang** [comment]
I see! Thanks! :)
